name = "ab-testing-worker"
main = "src/index.ts"
compatibility_date = "2024-02-27"

[[d1_databases]]
binding = "DB"
database_name = "ab-testing-db"
database_id = "060b7f35-736c-4805-9166-e22d92558466"
